### ISSUE TITLE
Include AbortController/Signal polyfill automatically?

### ISSUE THREAD

**Issue by jayphelps** [Netflix/yetch#3]
AbortController/Signal needs to be polyfilled separately, before including the yetch polyfill. It's not currently included automatically because they aren't technically specific to window.fetch (just like Promises aren't). It was thought that perhaps they may already have their own preferred polyfill. 

However, right now very few people will use AbortController/Signal for things other than fetch. My gut says it's _very_ confusing to the average dev that they need to include the extra polyfill, and many not realize that even though we have warnings as such.

Should we include a polyfill for AbortController/Signal automatically? e.g. https://github.com/mo/abortcontroller-polyfill/

I imagine we'd import the CJS exports from mo/abortcontroller-polyfill, re-export them from the `"main"` and then do the patching of the globals ourselves if they use `import 'yetch/polyfill'`. That way we don't update the global if they just do `import { fetch } from 'yetch'`

Cc/ @jamesplease @stefanpenner

**Comment by stefanpenner** [comment]
I suspect auto-including would make sense, e.g. following the "principle of least surprise".
Obviously if it is very heavy, then not. But It seems to not be.

**Comment by jamesplease** [comment]
> However, right now very few people will use AbortController/Signal for things other than fetch.

This seems likely to me.

> My gut says it's very confusing to the average dev that they need to include the extra polyfill, and many not realize that even though we have warnings as such.

Agreed.

> I imagine we'd import the CJS exports from mo/abortcontroller-polyfill, re-export them from the "main" and then do the patching of the globals ourselves if they use import 'yetch/polyfill'. That way we don't update the global if they just do import { fetch } from 'yetch'

:+1: This approach sounds good to me.

Are you thinking that we would check for the existence of an existing AbortController/AbortSignal, and only patch them if they don't exist?

**Comment by jayphelps** [comment]
> Are you thinking that we would check for the existence of an existing AbortController/AbortSignal, and only patch them if they don't exist?

Yep.
