### ISSUE TITLE
Error while runnig ember serve

### ISSUE THREAD

**Issue by Skgtouch** [Netflix/yetch#6]
Node -v : 8.11.3
Npm -v : 5.6.0

D:\<project-folder>\node_modules\watch\main.js:73
    if (err) throw err;
             ^

Error: ENOTDIR: not a directory, scandir 
                      'D:\Codebase\new\node_modules\yetch\dist\yetchpolyfill.js'

**Comment by alexlafroscia** [comment]
Is `yetch` in your `node_modules` but the `dist` folder is missing? Or is the whole `yetch` folder missing?

**Comment by Skgtouch** [comment]
Solved the issue.
I don't know how ember-fetch module was getting installed twice of different version.

Deleted one folder and working fine.

Thanks for your response :+1:
